services:
  - type: web
    name: emoji-dynasty
    runtime: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: OWNER_ID
        sync: false
